CREATE TABLE USERS (
   ID                            BIGINT(16)      NOT NULL PRIMARY KEY AUTO_INCREMENT,
   USERNAME                      VARCHAR(10)    NOT NULL,
   PASSWORD                      VARCHAR(50),
   FIN_VIGENCIA_PASS             DATE,
   NOMBRE                        VARCHAR(50),
   APELLIDO1                     VARCHAR(50),
   APELLIDO2                     VARCHAR(50),
   EMAIL                         VARCHAR(50),
   ENABLED                       CHAR(1)        NOT NULL DEFAULT 'Y',

   CONSTRAINT AK_USERS_USERNAME UNIQUE (USERNAME),
   CONSTRAINT AK_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE AUTHORITY (
  ID            BIGINT(16)       NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_ID       BIGINT(16)       NOT NULL,
  AUTHORITY     VARCHAR(50)     NOT NULL,
  
  CONSTRAINT FK_AUTHORITY_USUARIO FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);
