CREATE TABLE USERS (
   ID                            BIGINT(16)      NOT NULL PRIMARY KEY AUTO_INCREMENT,
   USERNAME                      VARCHAR(10)    NOT NULL,
   PASSWORD                      VARCHAR(50),
   FIN_VIGENCIA_PASS             DATE,
   NOMBRE                        VARCHAR(50),
   APELLIDO1                     VARCHAR(50),
   APELLIDO2                     VARCHAR(50),
   EMAIL                         VARCHAR(50),
   ENABLED                       CHAR(1)        NOT NULL DEFAULT 'Y',

   CONSTRAINT AK_USERS_USERNAME UNIQUE (USERNAME),
   CONSTRAINT AK_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE AUTHORITY (
  ID            BIGINT(16)       NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USER_ID       BIGINT(16)       NOT NULL,
  AUTHORITY     VARCHAR(50)     NOT NULL,
  
  CONSTRAINT FK_AUTHORITY_USUARIO FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE  STREAM (
    ID            BIGINT(16)       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_ID       BIGINT(16)       NOT NULL,
    NAME          VARCHAR(200)     NOT NULL,
  
    CONSTRAINT FK_STREAM_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE TABLE  FLOW (
    ID            BIGINT(16)       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    STREAM_ID     BIGINT(16)       NOT NULL,
    USER_ID       BIGINT(16)       NOT NULL,
    NAME          VARCHAR(200)     NOT NULL,
  
    CONSTRAINT FK_FLOW_STREAM FOREIGN KEY (STREAM_ID) REFERENCES STREAM (ID) ON DELETE CASCADE,
    CONSTRAINT FK_FLOW_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE  MESSAGE (
    ID            BIGINT(16)       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CONTENT       VARCHAR(5000)    NOT NULL,
    USER_ID       BIGINT(16)       NOT NULL,
    FLOW_ID       BIGINT(16)       NOT NULL,
    MSG_TIME      DATETIME         NOT NULL,
  
    CONSTRAINT FK_MESSAGE_FLOW FOREIGN KEY (FLOW_ID) REFERENCES FLOW (ID) ON DELETE CASCADE,
    CONSTRAINT FK_MESSAGE_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

INSERT INTO USERS (ID, USERNAME, PASSWORD, FIN_VIGENCIA_PASS, EMAIL, NOMBRE) VALUES (1, 'demo', sha1('demo{1}'), '2020-12-31', 'demo@domain.com', 'Demo user');
INSERT INTO USERS (ID, USERNAME, PASSWORD, FIN_VIGENCIA_PASS, EMAIL, NOMBRE) VALUES (2, 'admin', sha1('admin{2}'), '2020-12-31', 'admin@domain.com', 'Administrator');

INSERT INTO AUTHORITY (USER_ID, AUTHORITY) VALUES ((SELECT id FROM users WHERE username = 'admin'), 'ROLE_ADMIN');
INSERT INTO AUTHORITY (USER_ID, AUTHORITY) SELECT id, 'ROLE_USER' FROM USERS;

INSERT INTO STREAM (USER_ID, NAME) VALUES (3, 'Main Stream');

INSERT INTO FLOW (STREAM_ID, USER_ID, NAME) VALUES (1, 3, 'Flow 1');
INSERT INTO FLOW (STREAM_ID, USER_ID, NAME) VALUES (1, 3, 'Flow 2');